version: '3.7'

services:
    aplication:
        container_name: diccionario_web
        build: .
        volumes:
          - type: bind
            source: ./
            target: /app
          - /app/node_modules
        ports:
        - "80:3000"
        restart: always
